version: "3.9"
services:

  db:
    image: postgres:latest

    container_name: local_pgdb

    restart: always

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  web:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    
    ports:
      - "8000:8000"

    env_file:
      - .env
      
      
    depends_on:
      - db


volumes:
  postgres_data:

