# Generated by Django 4.2.1 on 2023-05-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_phonenumber_confirmed_remove_phonenumber_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='PhoneNumberManager',
        ),
        migrations.AddField(
            model_name='user',
            name='other_details',
            field=models.TextField(blank=True, default={'availability': 'Yes', 'dark_mode': 'No', 'language': 'English', 'notifications': 'On'}),
        ),
    ]
