# Generated by Django 4.2.1 on 2023-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_phonenumber_phonenumbermanager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('image', models.FileField(blank=True, upload_to='media/')),
                ('price', models.IntegerField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WashCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
                ('extra_per_item', models.IntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, to='core.washitem')),
            ],
        ),
    ]
