# Generated by Django 4.2.1 on 2023-05-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_washitem_washcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WashCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='WashItem',
            new_name='Item',
        ),
    ]
